image: archlinux
packages:
  - nodejs
  - yarn
sources:
  - https://git.sr.ht/~statianzo/slate-edit-table
secrets:
  - fefb2147-00f4-4b7e-a246-2007976291df
tasks:
  - setup: |
      cd slate-edit-table
      yarn --frozen-lockfile
  - build: |
      cd slate-edit-table
      yarn run build
  - test: |
      cd slate-edit-table
      yarn test
  - mirror: |
      cd slate-edit-table
      git push --mirror https://statianzo:$GITHUB_TOKEN@github.com/statianzo/slate-edit-table
