image: archlinux
packages:
  - nodejs
  - yarn
sources:
  - https://git.sr.ht/~statianzo/slate-edit-table
tasks:
  - setup: |
      cd slate-edit-table
      yarn --frozen-lockfile
  - build: |
      cd slate-edit-table
      yarn run build
  - test: |
      cd slate-edit-table
      yarn test
